import { and, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { chunks } from "@/db/schema";
import type { ChunkRow } from "./chunk.types";
import type { Chunk } from "@/services/rag/chunker";

/**
 * The tsvector column is generated by Postgres from the text, so nothing here
 * writes it. That is the point: it cannot drift from the text it indexes.
 */
export async function replaceChunksForSource(input: {
  sourceId: string;
  notebookId: string;
  chunks: Chunk[];
  embeddingModel: string;
  embeddingDim: number;
}): Promise<ChunkRow[]> {
  // A re-index replaces the whole set atomically, so retrieval never sees a
  // half swapped source.
  return db.transaction(async (tx) => {
    await tx.delete(chunks).where(eq(chunks.sourceId, input.sourceId));

    if (input.chunks.length === 0) return [];

    return tx
      .insert(chunks)
      .values(
        input.chunks.map((chunk) => ({
          sourceId: input.sourceId,
          notebookId: input.notebookId,
          chunkIndex: chunk.chunkIndex,
          text: chunk.text,
          tokenCount: chunk.tokenCount,
          locator: chunk.locator,
          embeddingModel: input.embeddingModel,
          embeddingDim: input.embeddingDim,
        })),
      )
      .returning();
  });
}

export async function listChunksForSource(sourceId: string): Promise<ChunkRow[]> {
  return db.select().from(chunks).where(eq(chunks.sourceId, sourceId)).orderBy(chunks.chunkIndex);
}

export async function countChunksForSource(sourceId: string): Promise<number> {
  const [row] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(chunks)
    .where(eq(chunks.sourceId, sourceId));
  return row?.count ?? 0;
}

export async function findChunksByIds(notebookId: string, ids: string[]): Promise<ChunkRow[]> {
  if (ids.length === 0) return [];
  return db
    .select()
    .from(chunks)
    .where(and(eq(chunks.notebookId, notebookId), inArray(chunks.id, ids)));
}

export async function deleteChunksForSource(sourceId: string): Promise<void> {
  await db.delete(chunks).where(eq(chunks.sourceId, sourceId));
}
