import { sql, type SQL } from "drizzle-orm";
import {
  pgTable,
  uuid,
  text,
  integer,
  jsonb,
  index,
  uniqueIndex,
  customType,
} from "drizzle-orm/pg-core";
import { notebooks } from "./notebooks";
import { sources } from "./sources";
import type { Locator } from "@/types/domain";

const tsvector = customType<{ data: string; driverData: string }>({ dataType: () => "tsvector" });

export const chunks = pgTable(
  "chunks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => sources.id, { onDelete: "cascade" }),
    // Denormalised from sources so that the keyword channel can filter by
    // notebook without a join, and so the isolation filter is one predicate.
    notebookId: uuid("notebook_id")
      .notNull()
      .references(() => notebooks.id, { onDelete: "cascade" }),

    chunkIndex: integer("chunk_index").notNull(),
    text: text("text").notNull(),
    tokenCount: integer("token_count").notNull(),

    locator: jsonb("locator").$type<Locator>().notNull(),

    embeddingModel: text("embedding_model").notNull(),
    embeddingDim: integer("embedding_dim").notNull(),

    // The Qdrant point id. Null until the source finishes embedding, since
    // vectors are written only after every embedding for the source succeeds.
    vectorId: uuid("vector_id"),

    // The keyword channel searches this. Generated by Postgres rather than
    // written by the application, so it can never drift from text.
    tsv: tsvector("tsv").generatedAlwaysAs((): SQL => sql`to_tsvector('english', ${chunks.text})`),
  },
  (table) => [
    index("chunks_source_id_idx").on(table.sourceId),
    index("chunks_notebook_id_idx").on(table.notebookId),
    uniqueIndex("chunks_source_chunk_index_key").on(table.sourceId, table.chunkIndex),
    index("chunks_tsv_idx").using("gin", table.tsv),
  ],
);

export type Chunk = typeof chunks.$inferSelect;
export type NewChunk = typeof chunks.$inferInsert;
